import Image from 'next/image'
import Link from "next/link";

export const metadata = {
  title: 'About | Keith',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <section className="bg-blue-700">
        <nav className="pt-10">
          <h1>Developed by Keith</h1>
        </nav>
      </section>
    </main>
  )
}



